<script setup lang="ts">
import { onMounted, onUnmounted, ref, computed, watch, nextTick } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { Message, CircleCheckFilled, CircleCloseFilled } from '@element-plus/icons-vue'; import { api, getMailboxes } from '../api/client'; import MailboxTable from '../components/MailboxTable.vue'; import DashboardMetricCard from '../components/DashboardMetricCard.vue'; import type { MailboxPayload } from '../types/api'
const data=ref<MailboxPayload>({counts:{},rows:[]}); const content=ref(''); const filter=ref('all'); const searchText=ref(''); const selected=ref<number[]>([]); const mailboxTable=ref<{clearSelection:()=>void}|null>(null); const latestCodes=ref<Record<number,string>>({}); const loadingLines=ref<number[]>([]); const currentPage=ref(1); const pageSize=ref(50); const countLabels:Record<string,string>={available:'邮箱可用总数',success:'成功数量',failed:'失败数量'}; const metricIcons:any={available:Message,success:CircleCheckFilled,failed:CircleCloseFilled}; let timer=0
const rows=computed(()=>data.value.rows.filter(row=>{const matchesFilter=filter.value==='all'||(filter.value==='not_success'?row.status!=='success':row.status===filter.value); const query=searchText.value.trim().toLowerCase(); const haystack=[row.email,row.password,row.status,row.status_label,row.error,row.reason].join(' ').toLowerCase(); return matchesFilter&&(!query||haystack.includes(query))}))
const pageRows=computed(()=>rows.value.slice((currentPage.value-1)*pageSize.value,currentPage.value*pageSize.value))
watch([filter,searchText],()=>{currentPage.value=1})
async function refresh(){try{data.value=await getMailboxes()}catch(e:any){ElMessage.error(e.message)}}
function applyMailboxPayload(payload:any){const next=payload?.mailboxes||payload;if(next&&Array.isArray(next.rows))data.value={counts:next.counts||{},rows:next.rows}}
async function append(){try{const result:any=await api('/api/mailboxes/import',{pool_content:content.value}); content.value=''; applyMailboxPayload(result); ElMessage.success(`已追加 ${result.imported||0} 条`)}catch(e:any){ElMessage.error(e.message)}}
async function mutate(path:string, message:string){if(!selected.value.length){ElMessage.warning('请先选择邮箱');return}try{await ElMessageBox.confirm(message,'确认操作',{type:'warning'});const lineNos=[...selected.value];const result:any=await api(path,{line_nos:lineNos});mailboxTable.value?.clearSelection();selected.value=[];applyMailboxPayload(result);await nextTick();mailboxTable.value?.clearSelection();if(path.endsWith('/delete')){latestCodes.value={};loadingLines.value=[]}ElMessage.success('操作完成')}catch(e:any){if(e!=='cancel')ElMessage.error(e.message||String(e))}}
async function code(line:number){if(loadingLines.value.includes(line))return; loadingLines.value=[...loadingLines.value,line]; try{const result:any=await api('/api/mailboxes/latest-code',{line_no:line});latestCodes.value[line]=result.code||'暂无';ElMessage.success(result.code?`验证码：${result.code}`:'未查到验证码')}catch(e:any){latestCodes.value[line]='暂无';ElMessage.error(e.message)}finally{loadingLines.value=loadingLines.value.filter(item=>item!==line)}}
onMounted(async()=>{await refresh();timer=window.setInterval(refresh,3000)});onUnmounted(()=>window.clearInterval(timer))
</script>
<template><div class="page"><el-row :gutter="8" class="content"><el-col :xs="24" :lg="24"><el-card shadow="never"><template #header><div class="import-header"><span>批量追加导入</span><el-button type="primary" class="append" @click="append"><el-icon><Upload /></el-icon>追加导入</el-button></div></template><el-input v-model="content" type="textarea" :rows="5" placeholder="邮箱----取码地址&#10;邮箱----密码----client_id----refresh_token&#10;GPT账号|登录密码|2FA密钥&#10;导入会追加到现有邮箱池，完全重复的行会自动跳过。" /></el-card></el-col><el-col :xs="24" :lg="24"><el-card shadow="never" class="table-card"><template #header><div class="header-row"><span>邮箱状态</span><div><el-input v-model="searchText" clearable size="small" placeholder="搜索邮箱、密码、状态" style="width:190px" /><el-select v-model="filter" size="small" style="width:120px"><el-option label="全部" value="all"/><el-option label="未成功" value="not_success"/><el-option label="可领取" value="available"/><el-option label="运行中" value="running"/><el-option label="成功" value="success"/><el-option label="失败" value="failed"/></el-select><el-button size="small" @click="mutate('/api/mailboxes/restore','将选中邮箱放回可领取状态？')">放回可领取</el-button><el-button size="small" type="danger" plain @click="mutate('/api/mailboxes/delete','确定删除选中的邮箱？')">删除选中</el-button></div></div></template><div class="metrics"><DashboardMetricCard v-for="key in ['available','success','failed']" :key="key" :title="countLabels[key]" :value="data.counts[key] || 0" :icon="metricIcons[key]" :tone="key === 'success' ? 'success' : key === 'failed' ? 'danger' : 'primary'" /></div><MailboxTable ref="mailboxTable" :rows="pageRows" :latest-codes="latestCodes" :loading-lines="loadingLines" @select="selected=$event" @code="code" /><el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" class="pager" small background layout="total, sizes, prev, pager, next" :page-sizes="[25,50,100]" :total="rows.length" /></el-card></el-col></el-row></div></template>
<style scoped>.page{height:100%;padding:2px}.content{height:100%;margin-top:0;display:flex;flex-direction:column;flex-wrap:nowrap}.content>.el-col{width:100%;max-width:100%;min-height:0}.content>.el-col:first-child{height:auto;flex:0 0 auto}.content>.el-col:last-child{height:auto;flex:1 1 auto}.content>.el-col:first-child>.el-card{height:auto;overflow:hidden}.import-header{display:flex;align-items:center;justify-content:space-between;gap:8px}.append{margin:0}.hint{font-size:12px;color:var(--el-text-color-secondary);line-height:1.45;margin:5px 0 0}.header-row{display:flex;justify-content:space-between;align-items:center;gap:8px}.header-row>div{display:flex;gap:6px;align-items:center}.table-card{height:100%;min-height:0;display:flex;flex-direction:column}.table-card>:deep(.el-card__body){min-height:0;flex:1;display:flex;flex-direction:column;padding:10px}.table-card :deep(.mailbox-table){flex:1;min-height:0}.pager{flex:0 0 auto;margin-top:8px;justify-content:flex-end}.metrics{display:flex;gap:8px;margin-bottom:8px}.metric-card{flex:1;min-width:0;padding:0}@media(max-width:560px){.metrics{flex-wrap:wrap}.metric-card{flex:1 1 calc(50% - 4px)}}</style>
