<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getLocalConfig, getSecret, getState, preflightRun, saveConfig, startRun, stopRun } from '../api/client'
import SettingsForm from '../components/SettingsForm.vue'; import LocalConfigActions from '../components/LocalConfigActions.vue'; import RunActions from '../components/RunActions.vue'; import RuntimeMetrics from '../components/RuntimeMetrics.vue'; import TaskResultsPanel from '../components/TaskResultsPanel.vue'; import LogPanel from '../components/LogPanel.vue'
const state = ref<any>({ runtime: {}, settings: {} }); const form = reactive<any>({ proxy:'http://127.0.0.1:7897', proxy_scope:{sms:false,email:false,upload:false}, target_count:'1', concurrency:'5', node_concurrency:'5', node_timeout:45, auth_session_retries:0, password:'', node_runner:'', sms_provider:'smsbower', sms_min_price:'0.01', max_price:'0.1', sms_timeout:'30', phone_max_attempts:0, nvtoken:{}, sub2api:{} }); const saving=ref(false); const preflighting=ref(false); let timer = 0
const running = () => !!state.value.runtime?.running; const hasPool = () => Number(state.value.runtime?.pool?.available || 0) > 0
function sync(payload:any){ state.value = payload.state || payload }
async function refresh(){ try { sync(await getState()) } catch {} }
async function load(){ try { const [s, c] = await Promise.all([getState(), getLocalConfig()]); sync(s); Object.assign(form, state.value.settings || {}, c.config || {}); const secrets=[{id:'sms_api_key',masked:form.sms_api_key,set:(value:string)=>form.sms_api_key=value},{id:'sub2_password',masked:form.sub2api?.password,set:(value:string)=>form.sub2api.password=value},{id:'nvtoken_api_key',masked:form.nvtoken?.api_key,set:(value:string)=>form.nvtoken.api_key=value}]; await Promise.all(secrets.filter(item=>item.masked==='********').map(async item=>{try{item.set((await getSecret(item.id)).value)}catch{}})) } catch (e:any) { ElMessage.error(e.message) } }
async function save(){saving.value=true;try{await saveConfig(form);ElMessage.success('配置已保存');await refresh()}catch(e:any){ElMessage.error(e.message)}finally{saving.value=false}}
async function preflight(){preflighting.value=true;try{await preflightRun({...form});ElMessage.success('真实链路预检通过');await refresh()}catch(e:any){ElMessage.error(e.message)}finally{preflighting.value=false}}
async function start(){ try { await startRun({...form}); ElMessage.success('任务已启动'); await refresh() } catch(e:any){ ElMessage.error(e.message) } }
async function stop(){ try { await stopRun(); ElMessage.success('已发送停止请求'); await refresh() } catch(e:any){ ElMessage.error(e.message) } }
onMounted(async()=>{ await load(); timer = window.setInterval(refresh, 1200) }); onUnmounted(()=>window.clearInterval(timer))
</script>
<template><div class="page"><el-row :gutter="12" class="content"><el-col :xs="24" :lg="9"><el-card shadow="never"><SettingsForm :model-value="form" @update:model-value="Object.assign(form, $event)" /><LocalConfigActions :model-value="form" @update:model-value="Object.assign(form, $event)" /><RunActions :running="running()" :has-pool="hasPool()" :saving="saving" :preflighting="preflighting" @save="save" @preflight="preflight" @start="start" @stop="stop" /></el-card></el-col><el-col :xs="24" :lg="15"><el-card shadow="never" class="stack"><RuntimeMetrics :runtime="state.runtime" /><el-divider content-position="center">任务结果</el-divider><div class="task-section"><TaskResultsPanel :tasks="state.runtime?.tasks || []" /></div><el-divider content-position="center">运行日志</el-divider><div class="log-section"><LogPanel :logs="state.logs || state.runtime?.logs || []" /></div></el-card></el-col></el-row></div></template>
<style scoped>.page{height:100%;padding:2px}.content{height:calc(100% - 8px);margin-top:8px}.content>.el-col{height:100%}.content>.el-col>.el-card{height:100%;display:flex;flex-direction:column}.content>.el-col>.el-card>:deep(.el-card__body){min-height:0;flex:1;overflow:auto}.stack{min-height:0}.content>.el-col>.stack>:deep(.el-card__body){display:flex;flex-direction:column;overflow:hidden!important}.stack :deep(.el-divider){flex:0 0 auto}.task-section{min-height:0;flex:1.1;overflow:hidden}.log-section{min-height:0;flex:1;overflow:hidden}.header-row{display:flex;justify-content:space-between;align-items:center}</style>
